services:
#Servicio mongoDB
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


#Servicio mongo-express
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: hlanz
    depends_on:
      - mongo

#Servicio backend
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://root:example@mongo:27017/auth_db?authSource=admin"
      JWT_SECRET: tu_clave_secreta
    depends_on:
      - mongo
#Servicio nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - backend


volumes:
  mongo_data:

