services:
  backend:
    build: .
    container_name: upload-backend
    ports:
      - "8050:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    volumes:
      - ./uploads:/app/uploads:rw
      - ./recycled:/app/recycled:rw
      - ./public:/app/public:ro
    user: "1000:1000"
    restart: unless-stopped

volumes:
  uploads:
  recycled:
  
